### ISSUE TITLE
Creating a Template code sample line #28.

### ISSUE THREAD

**Issue by mel510** [learn-co-curriculum/js-templates-intro-to-templates-readme#1]
Shouldn't this return` commenterDiv` so the  `p` is wrapped in a `div`, otherwise why was the variable created for it?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
