### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by logemerson** [learn-co-curriculum/js-templates-intro-to-templates-readme#2]
<img width="873" alt="screen shot 2017-11-10 at 3 09 41 pm" src="https://user-images.githubusercontent.com/28125427/32676678-834ac426-c629-11e7-82cf-8c401f6cc194.png">

"writting" ==> writing

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We corrected the readme.

As always thank you for contributing!
