### ISSUE TITLE
createCommenterLabel should be returning commenterDiv instead of commenterLabel

### ISSUE THREAD

**Issue by Emanao** [learn-co-curriculum/js-templates-intro-to-templates-readme#4]
function createCommenterLabel(commenter) {
  var commenterDiv = document.createElement("div");
  var commenterLabel = document.createElement("p");
  commenterLabel.innerHTML = "posted by:&nbsp;";
  var commenterName = document.createElement("span");
  commenterName.innerHTML = commenter;
  commenterLabel.appendChild(commenterName);
  commenterDiv.appendChild(commenterLabel);
  return commenterLabel;
}

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
