### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/js-templates-intro-to-templates-readme#5]
We'll explain more about events later, but for now all you need to know is that this line **prevent** the default action of a form, which would be submitting and reloading the page. 

> "prevent" should read "prevents"

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
