### ISSUE TITLE
Comma should be before the end quote

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-templates-intro-to-templates-readme#6]
In the sentence below, the comma should be before the close quote:

Beyond the obvious reasons of "this is ugly and hard to type", 

Thank you.

**Comment by drakeltheryuujin** [comment]
Thanks again for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
