### ISSUE TITLE
Run-on sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-templates-intro-to-templates-readme#7]
This is a run-on sentence:
"We broke each function up along the lines of each section of the DOM we wish to manipulate, affording us the ability to more easily manage the structure of our comments in a more modular and composable way, rather than trying to do everything in one function which isn't that much of an improvement over just typing all the markup into a string."

Suggested rewrite:
"We broke up each function to align with each section of the DOM we wish to manipulate, affording us the ability to more easily manage the structure of our comments in a more modular and composable way. This is better than trying to do everything in one function, which isn't that much of an improvement over just typing all the markup into a string."

Thank you.

**Comment by drakeltheryuujin** [comment]
Thanks again for spotting reporting an issue. We have updated the materials and believe your issue to have been resolved.
