### ISSUE TITLE
Need a subject in this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-templates-intro-to-templates-readme#8]
This sentence is missing a subject before the verb "augment:"
"And augment our addComment function to take the values from the form."

Suggested rewrite:
"And let's augment our addComment function to take the values from the form."

Thank you.

**Comment by drakeltheryuujin** [comment]
Thanks! We have updated the materials and believe your issue to have been resolved. 💙
